# Generated by Django 6.0.4 on 2026-07-15 12:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('icon_class', models.CharField(default='fas fa-cogs', help_text="FontAwesome class name, e.g., 'fas fa-car-battery'", max_length=50)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='SKU/Part Number')),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, help_text='Price in USD', max_digits=10)),
                ('image', models.ImageField(blank=True, help_text='Upload part image', null=True, upload_to='parts/')),
                ('is_available', models.BooleanField(default=True, verbose_name='In Stock')),
                ('specifications', models.TextField(blank=True, help_text='Format: Key: Value, one per line')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parts', to='inventory.category')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
