# Generated by Django 6.0.4 on 2026-07-15 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('vehicle_make', models.CharField(max_length=50, verbose_name='Vehicle Make (e.g. Toyota)')),
                ('vehicle_model', models.CharField(max_length=50, verbose_name='Vehicle Model (e.g. Hilux)')),
                ('vehicle_year', models.IntegerField(verbose_name='Vehicle Year')),
                ('service_type', models.CharField(choices=[('diagnostics', 'Diagnostic Testing'), ('electrical_repairs', 'Electrical Repairs'), ('battery_replacement', 'Battery Replacement'), ('alternator_starter', 'Alternator/Starter Repairs'), ('troubleshooting', 'General Auto-Electrical Troubleshooting'), ('other', 'Other Service')], default='diagnostics', max_length=30)),
                ('preferred_date', models.DateField(verbose_name='Preferred Date')),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (8:00 AM - 12:00 PM)'), ('afternoon', 'Afternoon (12:00 PM - 5:00 PM)')], default='morning', max_length=20)),
                ('message', models.TextField(blank=True, verbose_name='Additional Details or Symptoms')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Contact Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
