# Generated by Django 6.0.4 on 2026-07-15 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Jazz Auto Electric', max_length=100)),
                ('phone', models.CharField(default='+263 77 245 6789', max_length=30)),
                ('phone_raw', models.CharField(default='+263772456789', help_text='Digits only with country code, e.g. +263772456789', max_length=30)),
                ('whatsapp', models.CharField(default='+263 77 245 6789', max_length=30)),
                ('whatsapp_url', models.TextField(default='https://wa.me/263772456789?text=Hi%20Jazz%20Auto%20Electric,%20I%20would%20like%20to%20inquire%20about%20your%20services%20or%20motor%20spares.')),
                ('email', models.EmailField(default='info@jazzautoelectric.co.zw', max_length=254)),
                ('address', models.TextField(default='Plot 104, Cripps Road, Graniteside, Harare, Zimbabwe')),
                ('hours_weekdays', models.CharField(default='Mon - Fri: 8:00 AM - 5:00 PM', max_length=100)),
                ('hours_saturday', models.CharField(default='Sat: 8:00 AM - 1:00 PM', max_length=100)),
                ('hours_sunday', models.CharField(default='Sun: Closed', max_length=100)),
                ('map_latitude', models.FloatField(default=-17.8485)),
                ('map_longitude', models.FloatField(default=31.0605)),
            ],
            options={
                'verbose_name': 'Company Profile',
                'verbose_name_plural': 'Company Profile',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('icon_class', models.CharField(default='fas fa-tools', help_text='FontAwesome icon class, e.g. fas fa-laptop-code', max_length=50)),
                ('description', models.TextField()),
                ('bullet_points', models.TextField(help_text='Enter bullet points, one per line')),
                ('order', models.IntegerField(default=0, help_text='Display order sequence')),
            ],
            options={
                'ordering': ['order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. Fleet Manager, Harare Driver', max_length=100)),
                ('rating', models.IntegerField(default=5, help_text='Rating out of 5 stars')),
                ('text', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='bookingrequest',
            name='service_type',
            field=models.CharField(default='diagnostics', max_length=50),
        ),
    ]
