# Generated by Django 4.2.30 on 2026-07-16 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_companyprofile_service_testimonial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='hero_subtitle',
            field=models.TextField(default="Harare's trusted specialists in high-end vehicle diagnostic testing, custom wiring, alternator & starter rebuilds, and direct retail of premium motor spares."),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hero_tag',
            field=models.CharField(default='ADVANCED AUTOMOTIVE ENGINEERING', max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='hero_title',
            field=models.CharField(default='Precision Auto-Electrical Repairs & Quality Spares', max_length=200),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='status_diagnostics_class',
            field=models.CharField(default='val-green', help_text='CSS class for styling: val-green (green), val-orange (yellow/orange), val-red (red)', max_length=50),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='status_diagnostics_queue',
            field=models.CharField(default='Active (Normal Wait)', max_length=100),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='status_location_text',
            field=models.CharField(default='Graniteside, Harare', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='email',
            field=models.EmailField(default='info@jazzautoelectrics.co.zw', max_length=254),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='name',
            field=models.CharField(default='Jazz Auto Electrics', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_raw',
            field=models.CharField(default='+26371', help_text='Digits only with country code, e.g. +263772456789', max_length=30),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='whatsapp',
            field=models.CharField(default='+263 71', max_length=30),
        ),
    ]
