# Generated by Django 4.2.30 on 2026-07-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_companyprofile_hero_subtitle_companyprofile_hero_tag_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyprofile',
            name='alt_phone',
            field=models.CharField(default='+263 77 425 5065', max_length=30),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='alt_phone_raw',
            field=models.CharField(default='+263774255065', max_length=30),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='facebook_url',
            field=models.URLField(default='https://www.facebook.com/profile.php?id=100064758844406'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='instagram_url',
            field=models.URLField(default='https://www.instagram.com/jazz_auto_electrics/'),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='slogan',
            field=models.CharField(default='Where Precision Meets Harmony', max_length=200),
        ),
        migrations.AddField(
            model_name='companyprofile',
            name='tiktok_url',
            field=models.URLField(default='https://www.tiktok.com/@jazzauto_electrics'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='address',
            field=models.TextField(default='Harare, Zimbabwe (Hybrid Mobile Workshop Nationwide)'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='hero_subtitle',
            field=models.TextField(default='Where precision meets harmony. We travel all around Zimbabwe offering mobile diagnostics, hybrid battery servicing, starter/alternator repairs, and genuine motor spares.'),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='hero_tag',
            field=models.CharField(default='HYBRIDS & NON-HYBRIDS SPECIALISTS', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='hero_title',
            field=models.CharField(default='Hybrid Mobile Workshop & Precision Auto Electrics', max_length=200),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone',
            field=models.CharField(default='+263 71 294 8625', max_length=30),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='phone_raw',
            field=models.CharField(default='+263712948625', help_text='Digits only with country code, e.g. +263712948625', max_length=30),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='status_diagnostics_queue',
            field=models.CharField(default='Active (Mobile Workshop Nationwide)', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='status_location_text',
            field=models.CharField(default='Harare & All Zimbabwe', max_length=100),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='whatsapp',
            field=models.CharField(default='+263 71 294 8625', max_length=30),
        ),
        migrations.AlterField(
            model_name='companyprofile',
            name='whatsapp_url',
            field=models.TextField(default='https://wa.me/263712948625?text=Hi%20Jazz%20Auto%20Electrics,%20I%20would%20like%20to%20inquire%20about%20your%20services%20or%20motor%20spares.'),
        ),
    ]
